name: Findings
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.16.2 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get_cli: ^1.8.4
  get: 4.6.6
  firebase_auth: ^4.10.0
  google_fonts: ^4.0.4
  font_awesome_flutter: ^10.5.0
  syncfusion_flutter_charts: ^23.1.36
  share_plus: ^7.1.0
  connectivity_plus: ^4.0.2
  firebase_storage: ^11.2.8
  image_picker: ^1.0.4
  permission_handler: ^11.0.1
  liquid_pull_to_refresh: ^3.0.1
#  icons_launcher: ^2.1.3

  flutter: 
    sdk: flutter
  firebase_core: ^2.16.0
  cloud_firestore: ^4.9.2

dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/
#icons_launcher:
#  image_path: "assets/logo.png"
#  platforms:
#    android:
#      enable: true
#    ios:
#      enable: true
