name: engro
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.16.2 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get_cli: ^1.8.4
  get: 4.6.6
#  flutter_native_splash: ^2.3.2
#  icons_launcher: ^2.1.3

  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/
#
#flutter_native_splash:
#  background_image: "assets/splash.png"
#
#icons_launcher:
#  image_path: "assets/logo.png"
#  platforms:
#    android:
#      enable: true
#    ios:
#      enable: true
